
# =============================================================================
# PACKAGE METADATA
# =============================================================================

[package]
name = "tachyon-verification"
version = "0.1.0"
edition = "2021"
rust-version = "1.89"
repository = "https://github.com/byt3forg3/tachyon"
license = "MIT OR Apache-2.0"
publish = false

# =============================================================================
# LIBRARIES & BINARIES
# =============================================================================

[[bin]]
name = "tachyon_stream"
path = "tachyon_stream.rs"

# [[bin]]
# name = "avalanche"
# path = "src/bin/avalanche.rs"  # TODO: create this file

# =============================================================================
# DEPENDENCIES
# =============================================================================

[dependencies]
tachyon = { path = "../algorithms/tachyon", default-features = false, features = ["std"] }
