
# =============================================================================
# PACKAGE METADATA
# =============================================================================

[package]
name = "tachyon-benchmarks"
version = "0.1.0"
edition = "2021"
rust-version = "1.89"
repository = "https://github.com/byt3forg3/tachyon"
license = "MIT OR Apache-2.0"
publish = false

# =============================================================================
# FEATURES
# =============================================================================

[features]
default = ["multithread"]
multithread = ["tachyon/multithread"]

# =============================================================================
# DEPENDENCIES
# =============================================================================

[dependencies]
tachyon = { path = "../algorithms/tachyon", default-features = false, features = ["std"] }
criterion = "0.8"
blake3 = { version = "1.8", features = ["rayon"] }
sha2 = "0.11"
gxhash = "3"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
rand = "0.10"
num_cpus = "1.17"
rayon = "1.11"

# =============================================================================
# LIBRARIES & BINARIES
# =============================================================================

[[bench]]
name = "throughput"
harness = false

[[bench]]
name = "backend_compare"
harness = false

[[bench]]
name = "bench_bpc"
harness = false

[[bench]]
name = "avalanche"
harness = false
